# Homework 0 — DSCI 552

**Name:** Jeong Hun Lee  
**USC ID:** 1240-693-517  
**Instructor:** Mohammad Reza Rajati

## 2. Setting up the Environment

## 4. Pandas

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### (b),(c)

In [11]:
df = pd.read_csv("Salaries.csv", index_col="playerID", skiprows = [1])
df.head()

           yearID teamID lgID  salary
playerID
bedrost01    1985    ATL   NL  550000
benedbr01    1985    ATL   NL  545000
campri01     1985    ATL   NL  633333
ceronri01    1985    ATL   NL  625000
chambch01    1985    ATL   NL  800000

### (d)

In [24]:
filtered_players = df[ ((df["teamID"] == "ATL")|(df["teamID"]== "HOU")) & (df["salary"] > 1_000_000)]
filtered_players.index

Index(['hornebo01', 'murphda05', 'suttebr01', 'ryanno01', 'hornebo01',
       'murphda05', 'suttebr01', 'ryanno01', 'griffke01', 'murphda05',
       ...
       'feldmsc01', 'gonzama01', 'gregelu01', 'lowrije01', 'neshepa01',
       'quallch01', 'rasmuco01', 'singljo02', 'sippto01', 'valbulu01'],
      dtype='object', name='playerID', length=595)

### (e)

In [25]:
atl_salary_stats = df[df["teamID"] == "ATL"]["salary"].describe()
atl_salary_stats

count    8.850000e+02
mean     2.207749e+06
std      3.434320e+06
min      6.000000e+04
25%      3.000000e+05
50%      6.000000e+05
75%      2.400000e+06
max      1.606180e+07
Name: salary, dtype: float64

## (f)

In [26]:
data_dict = {col: [] for col in df.columns}

for _, row in df.iterrows():
    for col in df.columns:
        data_dict[col].append(row[col])

data_dict.keys()

dict_keys(['yearID', 'teamID', 'lgID', 'salary'])

## (g)

In [27]:
new_df = pd.DataFrame(data_dict)

new_df.columns = list("abcdefghijklmnopqrstuvwxyz")[:len(new_df.columns)]

new_df.head()

      a    b   c       d
0  1985  ATL  NL  550000
1  1985  ATL  NL  545000
2  1985  ATL  NL  633333
3  1985  ATL  NL  625000
4  1985  ATL  NL  800000

## 5. Numpy

## (a)

In [28]:
import numpy as np

py_list = [
    [1, 2, 3],
    [4, 5, 6]
]

arr = np.array(py_list)
arr

array([[1, 2, 3],
       [4, 5, 6]])

## (b)

In [30]:
arr.ndim, arr.shape, arr.size, arr.dtype, arr.itemsize, arr.data

(2, (2, 3), 6, dtype('int64'), 8, <memory at 0x1583346c0>)

## (c)

In [31]:
reshaped = arr.reshape(3, 2)
flattened = arr.flatten()

reshaped, flattened

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([1, 2, 3, 4, 5, 6]))

## (d)

In [32]:
one_d = np.array([10, 20, 30, 40, 50])

one_d[1:4]

array([20, 30, 40])

In [34]:
arr[:, 1]      # all rows, column index 1

array([2, 5])

In [35]:
arr[0:2, 1:3]  # rows 0–1, columns 1–2

array([[2, 3],
       [5, 6]])

## (e)

In [36]:
arr.min(), arr.max(), arr.mean(), arr.sum(), arr.std()

(np.int64(1),
 np.int64(6),
 np.float64(3.5),
 np.int64(21),
 np.float64(1.707825127659933))

In [38]:
arr.argmin(), arr.argmax()

(np.int64(0), np.int64(5))

In [39]:
arr.dot(arr.T)

array([[14, 32],
       [32, 77]])

In [40]:
np.square(arr), np.sqrt(arr), np.abs(arr)

(array([[ 1,  4,  9],
        [16, 25, 36]]),
 array([[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [41]:
np.exp(arr), np.sign(arr), np.mod(arr, 2)

(array([[  2.71828183,   7.3890561 ,  20.08553692],
        [ 54.59815003, 148.4131591 , 403.42879349]]),
 array([[1, 1, 1],
        [1, 1, 1]]),
 array([[1, 0, 1],
        [0, 1, 0]]))

## (f)

In [42]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [43]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [47]:
np.concatenate([np.array([1, 2]), np.array([3, 4])])

array([1, 2, 3, 4])